server:
  port: 8350
spring:
  application:
    name: gili-eureka
  profiles:
    active: dev

  #Eureka\u5BA2\u6237\u7AEF\u4E0EEureka\u670D\u52A1\u7AEF\u8FDB\u884C\u901A\u4FE1\u7684\u5730\u5740
eureka:
  client:
    service-url:
      defaultZone: http://localhost:${server.port}/eureka #\u8BBE\u7F6E\u670D\u52A1\u6CE8\u518C\u4E2D\u5FC3\u7684\u5730\u5740
    register-with-eureka: false #\u4E0D\u628A\u81EA\u5DF1\u6CE8\u518C\u5230Eureka\u670D\u52A1\u5668\u4E2D\uFF0C\u672C\u8EAB\u662F\u670D\u52A1\u5668\uFF0C\u65E0\u9700\u6CE8\u518C
  server:
    enable-self-preservation: false #关闭保护机制，以确保注册中心将不可用的实例正确剔除
    eviction-interval-timer-in-ms: 5000 #（代表是5秒，单位是毫秒,清理失效服务的间隔 ）
